### ISSUE TITLE
Can you add curl support for PHP?

### ISSUE THREAD

**Issue by johnjelinek** [dcoxall/dcoxall-wordpress#1]
I'm not familiar with puppet yet, otherwise I'd just send a pull request.

**Comment by johnjelinek** [comment]
Steps to install curl:
- `sudo apt-get install curl php5-curl`
- `echo extension=curl.so >> /etc/php5/fpm/php.ini`
- `/etc/init.d/php5-fpm restart`

**Comment by johnjelinek** [comment]
I did notice that the php module you're dependent on seems to claim curl support: https://github.com/saz/puppet-php/blob/master/EXAMPLE#L50, however when I executed puppet, no change. I had to repeat those steps again. Thoughts?

**Comment by dcoxall** [comment]
Thanks for opening this... I will have a look today. What is the best way of checking this has worked?

**Comment by johnjelinek** [comment]
If you check phpinfo() you'll see curl in the output, otherwise, it won't
be there.

**Comment by dcoxall** [comment]
I now explicitly include curl and have checked the output from `phpinfo` and can confirm it includes curl.

**Comment by johnjelinek** [comment]
Hmm, interesting. I was going to submit a pull request with just the change you made, but I noticed that it didn't supply the php.ini change that was necessary situationally. I still had to do `echo extension=curl.so >> /etc/php5/fpm/php.ini`. Did this part work for you?

**Comment by dcoxall** [comment]
I didn't need that line. With the change I made I just made sure it ran and then created a file with `<?php phpinfo(); ?>` and visited that page. It included the curl section.

**Comment by johnjelinek** [comment]
Cool, I'll try it out again :).

**Comment by johnjelinek** [comment]
ok, confirmed, works for me :)
